# This is a playbook to
#  - setup modularity development environment,
#  - build docker image within a given compose url,
#  - run a set of tests

- name:  Setup modularity development environment
  hosts: localhost
  connection: local
  become: yes
  become_method: sudo
  vars:
    container_name: "boltron_container"
  tasks:

    - name: update all packages
      package:
        name: "*"
        state: latest

    - name: install list of packages
      package:
        name: "{{ item }}"
        state: latest
        enablerepo: updates-testing
      with_items:
        - git
        - make
        - pkgwat
        - module-build-service
        - python2-modulemd
        - python2-pdc-client
        - mock-scm
        - docker
        - python-docker-py
        - atomic

    - name: create docker group
      group:
        name: docker
        state: present

    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: chown docker_sock
      file:
        path: /var/run/docker.sock
        owner: root
        group: docker

    - name: install mock packages
      shell: dnf install -y --allowerasing "{{ item }}"
      #  state: latest
      #shell: dnf install -y --allowerasing  "https://kojipkgs.fedoraproject.org//packages/mock/1.3.4/1.fc26/noarch/{{ item }}-1.3.4-1.fc26.noarch.rpm"
      with_items:
        - mock-lvm
        - mock-scm
        - mock

    - name: install list of packages
      package:
        name: "{{ item }}"
        state: latest
      with_items:
        - python3-solv
        - python3-click
        - fedora-packager
        - python3-solv
        - python3-click

    - name: pull bontron-preview container
      docker:
        name: boltron-preview
        image: modularitycontainers/boltron-preview
        state: present

    - name: create modularity-tools dir
      file:
        path: ~/modularity-tools/
        state: directory

    - name: git clone
      git:
        repo: https://github.com/fedora-modularity/baseruntime-package-lists.git
        dest: ~/modularity-tools/baseruntime-package-lists

    - name: git clone
      git:
        repo: https://github.com/fedora-modularity/depchase.git
        dest: ~/modularity-tools/depchase


    - name: copy boltron.cfg in /etc/mock
      command: cp data/boltron.cfg /etc/mock

    - name: build an image
      shell: data/build-image.sh "{{ compose }}"
      #abort play if the image can't be build for some reason
      when: '"https" in "{{ compose }}"'
      ignore_errors: false

#    - name: pull a docker image
#      command: docker pull "{{ compose }}"
#      when: '"registry" in "{{ compose }}"'
#      ignore_errors: false
#
#    - name: rename docker image if pulled
#      command: docker tag "{{ compose }}":latest boltron:latest
#      when: '"registry" in "{{ compose }}"'
#
#    - name: install python-docker-py to use docker_container
#      package:
#        name: python-docker-py
#        state: latest
#
    - name: create a data container
      docker_container:
        name: "{{ container_name }}"
        image: boltron
        state: started
        command: sleep infinity

    - include: tests/quick_mini_test.yaml
    - include: tests/modules_install.yaml
    - include: tests/modules_update.yaml
