# This is a playbook to
#  - install and run docker
#  - pull Modular Fedora image
#  - run a set of tests

- name: Modular Fedora image testing
  hosts: localhost
  connection: local
  become: yes
  become_method: sudo
  vars:
    container_name: "boltron_container"
    compose: "{{ compose|mandatory }}"
  tasks:

    - name: install docker
      package:
        name: docker
        enablerepo: "*"
        state: present

    - name: start docker service
      service:
        name: docker
        state: started

    - name: pull a docker image
      command: docker load "{{ compose }}"
      #when: '"registry" in "{{ compose }}"'
      ignore_errors: false

    - name: rename docker image if pulled
      command: docker tag "{{ compose }}":latest boltron:latest
      #when: '"registry" in "{{ compose }}"'

    - name: install python-docker-py to use docker_container
      package:
        name: python-docker-py
        enablerepo: "*"
        state: latest

    - name: create a data container
      docker_container:
        name: "{{ container_name }}"
        image: boltron
        state: started
        #volumes:
        #   - /vagrant/run-tests.sh:/run-tests.sh:z
        command: sleep infinity

    - include: tests/quick_mini_test.yaml
    - include: tests/modules_install.yaml
    - include: tests/modules_update.yaml
